name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  arduino-mega:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:mega
          sketch-paths: |
            - firmware/v1/Garage_Door
            - firmware/v3/Home_Control
          enable-warnings-report: true
  attiny26:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install avr-gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-avr avr-libc binutils-avr make
      - name: Build V2
        working-directory: firmware/v2
        run: make
